"""Modification to History Log tables - 3

Revision ID: 04c5c21fa78a
Revises: 92954cae939f
Create Date: 2023-06-23 02:07:19.646783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04c5c21fa78a'
down_revision = '92954cae939f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cascadehistory', 'status_messages',
               existing_type=sa.VARCHAR(),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_column('cascadehistory', 'retry_number')
    op.drop_column('cascadehistory', 'process_status')
    op.alter_column('collectionhistory', 'status_messages',
               existing_type=sa.VARCHAR(),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_column('collectionhistory', 'retry_number')
    op.drop_column('collectionhistory', 'process_status')
    op.alter_column('nfthistorylog', 'status_messages',
               existing_type=sa.VARCHAR(),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_column('nfthistorylog', 'retry_number')
    op.drop_column('nfthistorylog', 'process_status')
    op.alter_column('sensehistory', 'status_messages',
               existing_type=sa.VARCHAR(),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_column('sensehistory', 'retry_number')
    op.drop_column('sensehistory', 'process_status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sensehistory', sa.Column('process_status', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('sensehistory', sa.Column('retry_number', sa.INTEGER(), autoincrement=False, nullable=True))
    op.alter_column('sensehistory', 'status_messages',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.add_column('nfthistorylog', sa.Column('process_status', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('nfthistorylog', sa.Column('retry_number', sa.INTEGER(), autoincrement=False, nullable=True))
    op.alter_column('nfthistorylog', 'status_messages',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.add_column('collectionhistory', sa.Column('process_status', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('collectionhistory', sa.Column('retry_number', sa.INTEGER(), autoincrement=False, nullable=True))
    op.alter_column('collectionhistory', 'status_messages',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.add_column('cascadehistory', sa.Column('process_status', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('cascadehistory', sa.Column('retry_number', sa.INTEGER(), autoincrement=False, nullable=True))
    op.alter_column('cascadehistory', 'status_messages',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    # ### end Alembic commands ###
