"""sense

Revision ID: 089816220a8a
Revises: a515a7c316cc
Create Date: 2022-12-13 13:45:03.292122

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '089816220a8a'
down_revision = 'a515a7c316cc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sense',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original_file_name', sa.String(), nullable=True),
    sa.Column('original_file_content_type', sa.String(), nullable=True),
    sa.Column('original_file_local_path', sa.String(), nullable=True),
    sa.Column('ipfs_link', sa.String(), nullable=True),
    sa.Column('aws_link', sa.String(), nullable=True),
    sa.Column('other_links', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('work_id', sa.String(), nullable=True),
    sa.Column('ticket_id', sa.String(), nullable=True),
    sa.Column('wn_file_id', sa.String(), nullable=True),
    sa.Column('wn_task_id', sa.String(), nullable=True),
    sa.Column('wn_fee', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('ticket_status', sa.String(), nullable=True),
    sa.Column('retry_num', sa.Integer(), nullable=True),
    sa.Column('reg_ticket_txid', sa.String(), nullable=True),
    sa.Column('act_ticket_txid', sa.String(), nullable=True),
    sa.Column('pastel_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('burn_txid', sa.String(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sense_act_ticket_txid'), 'sense', ['act_ticket_txid'], unique=False)
    op.create_index(op.f('ix_sense_burn_txid'), 'sense', ['burn_txid'], unique=False)
    op.create_index(op.f('ix_sense_height'), 'sense', ['height'], unique=False)
    op.create_index(op.f('ix_sense_id'), 'sense', ['id'], unique=False)
    op.create_index(op.f('ix_sense_pastel_id'), 'sense', ['pastel_id'], unique=False)
    op.create_index(op.f('ix_sense_reg_ticket_txid'), 'sense', ['reg_ticket_txid'], unique=False)
    op.create_index(op.f('ix_sense_ticket_id'), 'sense', ['ticket_id'], unique=False)
    op.create_index(op.f('ix_sense_ticket_status'), 'sense', ['ticket_status'], unique=False)
    op.create_index(op.f('ix_sense_wn_file_id'), 'sense', ['wn_file_id'], unique=False)
    op.create_index(op.f('ix_sense_wn_task_id'), 'sense', ['wn_task_id'], unique=False)
    op.create_index(op.f('ix_sense_work_id'), 'sense', ['work_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sense_work_id'), table_name='sense')
    op.drop_index(op.f('ix_sense_wn_task_id'), table_name='sense')
    op.drop_index(op.f('ix_sense_wn_file_id'), table_name='sense')
    op.drop_index(op.f('ix_sense_ticket_status'), table_name='sense')
    op.drop_index(op.f('ix_sense_ticket_id'), table_name='sense')
    op.drop_index(op.f('ix_sense_reg_ticket_txid'), table_name='sense')
    op.drop_index(op.f('ix_sense_pastel_id'), table_name='sense')
    op.drop_index(op.f('ix_sense_id'), table_name='sense')
    op.drop_index(op.f('ix_sense_height'), table_name='sense')
    op.drop_index(op.f('ix_sense_burn_txid'), table_name='sense')
    op.drop_index(op.f('ix_sense_act_ticket_txid'), table_name='sense')
    op.drop_table('sense')
    # ### end Alembic commands ###
