"""New type for preburn tnx status - BAD

Revision ID: 12e88a28d270
Revises: 6ad2ed9e8b81
Create Date: 2023-05-23 15:41:49.311793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12e88a28d270'
down_revision = '6ad2ed9e8b81'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    ### alter type pbtxstatus add value 'BAD' after 'USED';
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    ### alter type pbtxstatus drop value 'BAD';
    pass
    # ### end Alembic commands ###
