"""cascade tasks db updated

Revision ID: 169f89947086
Revises: 43eb58c6061f
Create Date: 2022-10-31 19:07:51.001543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '169f89947086'
down_revision = '43eb58c6061f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cascade', sa.Column('task_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_cascade_task_id'), 'cascade', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cascade_task_id'), table_name='cascade')
    op.drop_column('cascade', 'task_id')
    # ### end Alembic commands ###
