"""ew tables for Nft

Revision ID: 1c268ae760ae
Revises: 12e88a28d270
Create Date: 2023-05-23 17:39:44.229089

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1c268ae760ae'
down_revision = '12e88a28d270'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nft',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original_file_name', sa.String(), nullable=True),
    sa.Column('original_file_content_type', sa.String(), nullable=True),
    sa.Column('original_file_local_path', sa.String(), nullable=True),
    sa.Column('original_file_ipfs_link', sa.String(), nullable=True),
    sa.Column('stored_file_ipfs_link', sa.String(), nullable=True),
    sa.Column('stored_file_aws_link', sa.String(), nullable=True),
    sa.Column('stored_file_other_links', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('make_publicly_accessible', sa.Boolean(), nullable=True),
    sa.Column('work_id', sa.String(), nullable=True),
    sa.Column('ticket_id', sa.String(), nullable=True),
    sa.Column('wn_file_id', sa.String(), nullable=True),
    sa.Column('wn_task_id', sa.String(), nullable=True),
    sa.Column('wn_fee', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('ticket_status', sa.String(), nullable=True),
    sa.Column('retry_num', sa.Integer(), nullable=True),
    sa.Column('reg_ticket_txid', sa.String(), nullable=True),
    sa.Column('act_ticket_txid', sa.String(), nullable=True),
    sa.Column('pastel_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('burn_txid', sa.String(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nft_act_ticket_txid'), 'nft', ['act_ticket_txid'], unique=False)
    op.create_index(op.f('ix_nft_burn_txid'), 'nft', ['burn_txid'], unique=False)
    op.create_index(op.f('ix_nft_height'), 'nft', ['height'], unique=False)
    op.create_index(op.f('ix_nft_id'), 'nft', ['id'], unique=False)
    op.create_index(op.f('ix_nft_pastel_id'), 'nft', ['pastel_id'], unique=False)
    op.create_index(op.f('ix_nft_reg_ticket_txid'), 'nft', ['reg_ticket_txid'], unique=False)
    op.create_index(op.f('ix_nft_ticket_id'), 'nft', ['ticket_id'], unique=False)
    op.create_index(op.f('ix_nft_ticket_status'), 'nft', ['ticket_status'], unique=False)
    op.create_index(op.f('ix_nft_wn_file_id'), 'nft', ['wn_file_id'], unique=False)
    op.create_index(op.f('ix_nft_wn_task_id'), 'nft', ['wn_task_id'], unique=False)
    op.create_index(op.f('ix_nft_work_id'), 'nft', ['work_id'], unique=False)
    op.create_table('nfthistory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('wn_file_id', sa.String(), nullable=True),
    sa.Column('wn_task_id', sa.String(), nullable=True),
    sa.Column('task_status', sa.String(), nullable=True),
    sa.Column('status_messages', sa.String(), nullable=True),
    sa.Column('retry_number', sa.Integer(), nullable=True),
    sa.Column('pastel_id', sa.String(), nullable=True),
    sa.Column('nft_task_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['nft_task_id'], ['nft.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nfthistory_id'), 'nfthistory', ['id'], unique=False)
    op.create_index(op.f('ix_nfthistory_pastel_id'), 'nfthistory', ['pastel_id'], unique=False)
    op.create_index(op.f('ix_nfthistory_wn_file_id'), 'nfthistory', ['wn_file_id'], unique=False)
    op.create_index(op.f('ix_nfthistory_wn_task_id'), 'nfthistory', ['wn_task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_nfthistory_wn_task_id'), table_name='nfthistory')
    op.drop_index(op.f('ix_nfthistory_wn_file_id'), table_name='nfthistory')
    op.drop_index(op.f('ix_nfthistory_pastel_id'), table_name='nfthistory')
    op.drop_index(op.f('ix_nfthistory_id'), table_name='nfthistory')
    op.drop_table('nfthistory')
    op.drop_index(op.f('ix_nft_work_id'), table_name='nft')
    op.drop_index(op.f('ix_nft_wn_task_id'), table_name='nft')
    op.drop_index(op.f('ix_nft_wn_file_id'), table_name='nft')
    op.drop_index(op.f('ix_nft_ticket_status'), table_name='nft')
    op.drop_index(op.f('ix_nft_ticket_id'), table_name='nft')
    op.drop_index(op.f('ix_nft_reg_ticket_txid'), table_name='nft')
    op.drop_index(op.f('ix_nft_pastel_id'), table_name='nft')
    op.drop_index(op.f('ix_nft_id'), table_name='nft')
    op.drop_index(op.f('ix_nft_height'), table_name='nft')
    op.drop_index(op.f('ix_nft_burn_txid'), table_name='nft')
    op.drop_index(op.f('ix_nft_act_ticket_txid'), table_name='nft')
    op.drop_table('nft')
    # ### end Alembic commands ###
