"""1) Added funding_address to user and api_key; 2) Added paslte_id to api_key

Revision ID: 376d9eba0a8b
Revises: 9b55ce385361
Create Date: 2023-11-19 23:52:08.050772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '376d9eba0a8b'
down_revision = '9b55ce385361'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apikey', sa.Column('funding_address', sa.String(), nullable=True))
    op.add_column('apikey', sa.Column('pastel_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_apikey_funding_address'), 'apikey', ['funding_address'], unique=True)
    op.create_index(op.f('ix_apikey_pastel_id'), 'apikey', ['pastel_id'], unique=True)
    op.add_column('user', sa.Column('funding_address', sa.String(), nullable=True))
    op.create_index(op.f('ix_user_funding_address'), 'user', ['funding_address'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_funding_address'), table_name='user')
    op.drop_column('user', 'funding_address')
    op.drop_index(op.f('ix_apikey_pastel_id'), table_name='apikey')
    op.drop_index(op.f('ix_apikey_funding_address'), table_name='apikey')
    op.drop_column('apikey', 'pastel_id')
    op.drop_column('apikey', 'funding_address')
    # ### end Alembic commands ###
