"""cascade tasks db updated

Revision ID: 43eb58c6061f
Revises: 7677bfbbfe2b
Create Date: 2022-10-27 12:11:59.387536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43eb58c6061f'
down_revision = '7677bfbbfe2b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_cascade_last_task_id', table_name='cascade')
    op.drop_column('cascade', 'last_task_id')
    op.add_column('preburntx', sa.Column('ticket_id', sa.String(), nullable=True))
    op.drop_column('preburntx', 'task_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('preburntx', sa.Column('task_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('preburntx', 'ticket_id')
    op.add_column('cascade', sa.Column('last_task_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index('ix_cascade_last_task_id', 'cascade', ['last_task_id'], unique=False)
    # ### end Alembic commands ###
