"""cascade tasks db updated

Revision ID: 5714056d5e2b
Revises: b0e6bfee6eef
Create Date: 2022-10-25 15:03:44.996652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5714056d5e2b'
down_revision = 'b0e6bfee6eef'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
