"""cascade tasks db updated

Revision ID: 663ce8a6236b
Revises: b2f7cb07d3fc
Create Date: 2022-11-01 19:38:32.784472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '663ce8a6236b'
down_revision = 'b2f7cb07d3fc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cascade', sa.Column('pastel_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_cascade_pastel_id'), 'cascade', ['pastel_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cascade_pastel_id'), table_name='cascade')
    op.drop_column('cascade', 'pastel_id')
    # ### end Alembic commands ###
