"""cascade tasks db

Revision ID: 669a53466d02
Revises: eb0979214a76
Create Date: 2022-10-24 23:28:36.047112

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '669a53466d02'
down_revision = 'eb0979214a76'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cascade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('work_id', sa.Integer(), nullable=True),
    sa.Column('task_id', sa.String(), nullable=True),
    sa.Column('wn_task_id', sa.String(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cascade_height'), 'cascade', ['height'], unique=False)
    op.create_index(op.f('ix_cascade_id'), 'cascade', ['id'], unique=False)
    op.create_index(op.f('ix_cascade_work_id'), 'cascade', ['work_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cascade_work_id'), table_name='cascade')
    op.drop_index(op.f('ix_cascade_id'), table_name='cascade')
    op.drop_index(op.f('ix_cascade_height'), table_name='cascade')
    op.drop_table('cascade')
    # ### end Alembic commands ###
