"""Added new column make_publicly_accessible to cascade table

Revision ID: 6ad2ed9e8b81
Revises: e36d7436f379
Create Date: 2023-05-16 10:58:23.775928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ad2ed9e8b81'
down_revision = 'e36d7436f379'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cascade', sa.Column('make_publicly_accessible', sa.Boolean(), nullable=True))
    op.add_column('sense', sa.Column('make_publicly_accessible', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sense', 'make_publicly_accessible')
    op.drop_column('cascade', 'make_publicly_accessible')
    # ### end Alembic commands ###
