"""cascade tasks db updated

Revision ID: 7677bfbbfe2b
Revises: a4420003a0ed
Create Date: 2022-10-26 14:56:10.420429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7677bfbbfe2b'
down_revision = 'a4420003a0ed'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cascade', sa.Column('last_task_id', sa.String(), nullable=True))
    op.drop_index('ix_cascade_task_id', table_name='cascade')
    op.create_index(op.f('ix_cascade_last_task_id'), 'cascade', ['last_task_id'], unique=False)
    op.drop_column('cascade', 'task_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cascade', sa.Column('task_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_cascade_last_task_id'), table_name='cascade')
    op.create_index('ix_cascade_task_id', 'cascade', ['task_id'], unique=False)
    op.drop_column('cascade', 'last_task_id')
    # ### end Alembic commands ###
