"""Added Claimed PastelIDs table

Revision ID: 79f1b3288fdd
Revises: eafeaaa2b132
Create Date: 2023-06-26 22:11:34.600127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79f1b3288fdd'
down_revision = 'eafeaaa2b132'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('claimedpastelid',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pastel_id', sa.String(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_claimedpastelid_id'), 'claimedpastelid', ['id'], unique=False)
    op.create_index(op.f('ix_claimedpastelid_pastel_id'), 'claimedpastelid', ['pastel_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_claimedpastelid_pastel_id'), table_name='claimedpastelid')
    op.drop_index(op.f('ix_claimedpastelid_id'), table_name='claimedpastelid')
    op.drop_table('claimedpastelid')
    # ### end Alembic commands ###
