"""cascade tasks db updated

Revision ID: 7c043c1767f6
Revises: 089816220a8a
Create Date: 2022-12-13 18:17:50.087006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c043c1767f6'
down_revision = '089816220a8a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
