"""cascade tasks db updated

Revision ID: 828c83605fb0
Revises: 169f89947086
Create Date: 2022-11-01 17:39:27.314801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '828c83605fb0'
down_revision = '169f89947086'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cascade', sa.Column('ticket_status', sa.String(), nullable=True))
    op.drop_index('ix_cascade_task_id', table_name='cascade')
    op.create_index(op.f('ix_cascade_ticket_status'), 'cascade', ['ticket_status'], unique=False)
    op.drop_column('cascade', 'task_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cascade', sa.Column('task_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_cascade_ticket_status'), table_name='cascade')
    op.create_index('ix_cascade_task_id', 'cascade', ['task_id'], unique=False)
    op.drop_column('cascade', 'ticket_status')
    # ### end Alembic commands ###
