"""Added balance limit column

Revision ID: 83ae5272ec84
Revises: b2533f16d36d
Create Date: 2023-12-06 19:29:15.288744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83ae5272ec84'
down_revision = 'b2533f16d36d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apikey', sa.Column('balance_limit', sa.Float(), nullable=False))
    op.alter_column('apikey', 'balance',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.add_column('user', sa.Column('balance_limit', sa.Float(), nullable=False))
    op.alter_column('user', 'balance',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'balance',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.drop_column('user', 'balance_limit')
    op.alter_column('apikey', 'balance',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.drop_column('apikey', 'balance_limit')
    # ### end Alembic commands ###
