"""Added new tables - CascadeHistory and SenseHistory; Added is_public to RegTicket table

Revision ID: 96bfb91e2587
Revises: b80d68ab8877
Create Date: 2023-03-10 22:52:41.299746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96bfb91e2587'
down_revision = 'b80d68ab8877'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cascadehistory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('wn_file_id', sa.String(), nullable=True),
    sa.Column('wn_task_id', sa.String(), nullable=True),
    sa.Column('task_status', sa.String(), nullable=True),
    sa.Column('status_messages', sa.String(), nullable=True),
    sa.Column('retry_number', sa.Integer(), nullable=True),
    sa.Column('pastel_id', sa.String(), nullable=True),
    sa.Column('cascade_task_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cascade_task_id'], ['cascade.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cascadehistory_id'), 'cascadehistory', ['id'], unique=False)
    op.create_index(op.f('ix_cascadehistory_pastel_id'), 'cascadehistory', ['pastel_id'], unique=False)
    op.create_index(op.f('ix_cascadehistory_wn_file_id'), 'cascadehistory', ['wn_file_id'], unique=False)
    op.create_index(op.f('ix_cascadehistory_wn_task_id'), 'cascadehistory', ['wn_task_id'], unique=False)
    op.create_table('sensehistory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('wn_file_id', sa.String(), nullable=True),
    sa.Column('wn_task_id', sa.String(), nullable=True),
    sa.Column('task_status', sa.String(), nullable=True),
    sa.Column('status_messages', sa.String(), nullable=True),
    sa.Column('retry_number', sa.Integer(), nullable=True),
    sa.Column('pastel_id', sa.String(), nullable=True),
    sa.Column('sense_task_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sense_task_id'], ['sense.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sensehistory_id'), 'sensehistory', ['id'], unique=False)
    op.create_index(op.f('ix_sensehistory_pastel_id'), 'sensehistory', ['pastel_id'], unique=False)
    op.create_index(op.f('ix_sensehistory_wn_file_id'), 'sensehistory', ['wn_file_id'], unique=False)
    op.create_index(op.f('ix_sensehistory_wn_task_id'), 'sensehistory', ['wn_task_id'], unique=False)
    op.add_column('regticket', sa.Column('is_public', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('regticket', 'is_public')
    op.drop_index(op.f('ix_sensehistory_wn_task_id'), table_name='sensehistory')
    op.drop_index(op.f('ix_sensehistory_wn_file_id'), table_name='sensehistory')
    op.drop_index(op.f('ix_sensehistory_pastel_id'), table_name='sensehistory')
    op.drop_index(op.f('ix_sensehistory_id'), table_name='sensehistory')
    op.drop_table('sensehistory')
    op.drop_index(op.f('ix_cascadehistory_wn_task_id'), table_name='cascadehistory')
    op.drop_index(op.f('ix_cascadehistory_wn_file_id'), table_name='cascadehistory')
    op.drop_index(op.f('ix_cascadehistory_pastel_id'), table_name='cascadehistory')
    op.drop_index(op.f('ix_cascadehistory_id'), table_name='cascadehistory')
    op.drop_table('cascadehistory')
    # ### end Alembic commands ###
