"""cascade tasks db updated

Revision ID: a4420003a0ed
Revises: ead481e1f7a5
Create Date: 2022-10-26 13:11:53.503852

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a4420003a0ed'
down_revision = 'ead481e1f7a5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cascade', sa.Column('ipfs_link', sa.String(), nullable=True))
    op.add_column('cascade', sa.Column('aws_link', sa.String(), nullable=True))
    op.add_column('cascade', sa.Column('other_links', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('cascade', sa.Column('ticket_id', sa.String(), nullable=True))
    op.add_column('cascade', sa.Column('reg_ticket_txid', sa.String(), nullable=True))
    op.add_column('cascade', sa.Column('act_ticket_txid', sa.String(), nullable=True))
    op.create_index(op.f('ix_cascade_act_ticket_txid'), 'cascade', ['act_ticket_txid'], unique=False)
    op.create_index(op.f('ix_cascade_reg_ticket_txid'), 'cascade', ['reg_ticket_txid'], unique=False)
    op.create_index(op.f('ix_cascade_ticket_id'), 'cascade', ['ticket_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cascade_ticket_id'), table_name='cascade')
    op.drop_index(op.f('ix_cascade_reg_ticket_txid'), table_name='cascade')
    op.drop_index(op.f('ix_cascade_act_ticket_txid'), table_name='cascade')
    op.drop_column('cascade', 'act_ticket_txid')
    op.drop_column('cascade', 'reg_ticket_txid')
    op.drop_column('cascade', 'ticket_id')
    op.drop_column('cascade', 'other_links')
    op.drop_column('cascade', 'aws_link')
    op.drop_column('cascade', 'ipfs_link')
    # ### end Alembic commands ###
