"""cascade tasks db updated

Revision ID: a515a7c316cc
Revises: 663ce8a6236b
Create Date: 2022-11-08 18:18:12.968065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a515a7c316cc'
down_revision = '663ce8a6236b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cascade', sa.Column('retry_num', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cascade', 'retry_num')
    # ### end Alembic commands ###
