"""Modification to History Log tables - 1

Revision ID: a9b62278abcf
Revises: ff11ec2de390
Create Date: 2023-06-23 00:08:26.921067

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a9b62278abcf'
down_revision = 'ff11ec2de390'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cascadehistorylog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('wn_file_id', sa.String(), nullable=True),
    sa.Column('wn_task_id', sa.String(), nullable=True),
    sa.Column('pastel_id', sa.String(), nullable=True),
    sa.Column('status_messages', sa.String(), nullable=True),
    sa.Column('process_status', sa.String(), nullable=True),
    sa.Column('retry_number', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cascadehistorylog_id'), 'cascadehistorylog', ['id'], unique=False)
    op.create_index(op.f('ix_cascadehistorylog_pastel_id'), 'cascadehistorylog', ['pastel_id'], unique=False)
    op.create_index(op.f('ix_cascadehistorylog_task_id'), 'cascadehistorylog', ['task_id'], unique=False)
    op.create_index(op.f('ix_cascadehistorylog_wn_file_id'), 'cascadehistorylog', ['wn_file_id'], unique=False)
    op.create_index(op.f('ix_cascadehistorylog_wn_task_id'), 'cascadehistorylog', ['wn_task_id'], unique=False)
    op.create_table('collectionhistorylog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('wn_file_id', sa.String(), nullable=True),
    sa.Column('wn_task_id', sa.String(), nullable=True),
    sa.Column('pastel_id', sa.String(), nullable=True),
    sa.Column('status_messages', sa.String(), nullable=True),
    sa.Column('process_status', sa.String(), nullable=True),
    sa.Column('retry_number', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collectionhistorylog_id'), 'collectionhistorylog', ['id'], unique=False)
    op.create_index(op.f('ix_collectionhistorylog_pastel_id'), 'collectionhistorylog', ['pastel_id'], unique=False)
    op.create_index(op.f('ix_collectionhistorylog_task_id'), 'collectionhistorylog', ['task_id'], unique=False)
    op.create_index(op.f('ix_collectionhistorylog_wn_file_id'), 'collectionhistorylog', ['wn_file_id'], unique=False)
    op.create_index(op.f('ix_collectionhistorylog_wn_task_id'), 'collectionhistorylog', ['wn_task_id'], unique=False)
    op.create_table('nfthistorylog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('wn_file_id', sa.String(), nullable=True),
    sa.Column('wn_task_id', sa.String(), nullable=True),
    sa.Column('pastel_id', sa.String(), nullable=True),
    sa.Column('status_messages', sa.String(), nullable=True),
    sa.Column('process_status', sa.String(), nullable=True),
    sa.Column('retry_number', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nfthistorylog_id'), 'nfthistorylog', ['id'], unique=False)
    op.create_index(op.f('ix_nfthistorylog_pastel_id'), 'nfthistorylog', ['pastel_id'], unique=False)
    op.create_index(op.f('ix_nfthistorylog_task_id'), 'nfthistorylog', ['task_id'], unique=False)
    op.create_index(op.f('ix_nfthistorylog_wn_file_id'), 'nfthistorylog', ['wn_file_id'], unique=False)
    op.create_index(op.f('ix_nfthistorylog_wn_task_id'), 'nfthistorylog', ['wn_task_id'], unique=False)
    op.create_table('sensehistorylog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('wn_file_id', sa.String(), nullable=True),
    sa.Column('wn_task_id', sa.String(), nullable=True),
    sa.Column('pastel_id', sa.String(), nullable=True),
    sa.Column('status_messages', sa.String(), nullable=True),
    sa.Column('process_status', sa.String(), nullable=True),
    sa.Column('retry_number', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sensehistorylog_id'), 'sensehistorylog', ['id'], unique=False)
    op.create_index(op.f('ix_sensehistorylog_pastel_id'), 'sensehistorylog', ['pastel_id'], unique=False)
    op.create_index(op.f('ix_sensehistorylog_task_id'), 'sensehistorylog', ['task_id'], unique=False)
    op.create_index(op.f('ix_sensehistorylog_wn_file_id'), 'sensehistorylog', ['wn_file_id'], unique=False)
    op.create_index(op.f('ix_sensehistorylog_wn_task_id'), 'sensehistorylog', ['wn_task_id'], unique=False)
    op.drop_index('ix_nfthistory_id', table_name='nfthistory')
    op.drop_index('ix_nfthistory_pastel_id', table_name='nfthistory')
    op.drop_index('ix_nfthistory_wn_file_id', table_name='nfthistory')
    op.drop_index('ix_nfthistory_wn_task_id', table_name='nfthistory')
    op.drop_table('nfthistory')
    op.drop_index('ix_collectionhistory_id', table_name='collectionhistory')
    op.drop_index('ix_collectionhistory_pastel_id', table_name='collectionhistory')
    op.drop_index('ix_collectionhistory_wn_file_id', table_name='collectionhistory')
    op.drop_index('ix_collectionhistory_wn_task_id', table_name='collectionhistory')
    op.drop_table('collectionhistory')
    op.drop_index('ix_cascadehistory_id', table_name='cascadehistory')
    op.drop_index('ix_cascadehistory_pastel_id', table_name='cascadehistory')
    op.drop_index('ix_cascadehistory_wn_file_id', table_name='cascadehistory')
    op.drop_index('ix_cascadehistory_wn_task_id', table_name='cascadehistory')
    op.drop_table('cascadehistory')
    op.drop_index('ix_sensehistory_id', table_name='sensehistory')
    op.drop_index('ix_sensehistory_pastel_id', table_name='sensehistory')
    op.drop_index('ix_sensehistory_wn_file_id', table_name='sensehistory')
    op.drop_index('ix_sensehistory_wn_task_id', table_name='sensehistory')
    op.drop_table('sensehistory')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sensehistory',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('wn_file_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('wn_task_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('task_status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status_messages', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('retry_number', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('pastel_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('sense_task_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['sense_task_id'], ['sense.id'], name='sensehistory_sense_task_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='sensehistory_pkey')
    )
    op.create_index('ix_sensehistory_wn_task_id', 'sensehistory', ['wn_task_id'], unique=False)
    op.create_index('ix_sensehistory_wn_file_id', 'sensehistory', ['wn_file_id'], unique=False)
    op.create_index('ix_sensehistory_pastel_id', 'sensehistory', ['pastel_id'], unique=False)
    op.create_index('ix_sensehistory_id', 'sensehistory', ['id'], unique=False)
    op.create_table('cascadehistory',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('wn_file_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('wn_task_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('task_status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status_messages', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('retry_number', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('pastel_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('cascade_task_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['cascade_task_id'], ['cascade.id'], name='cascadehistory_cascade_task_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='cascadehistory_pkey')
    )
    op.create_index('ix_cascadehistory_wn_task_id', 'cascadehistory', ['wn_task_id'], unique=False)
    op.create_index('ix_cascadehistory_wn_file_id', 'cascadehistory', ['wn_file_id'], unique=False)
    op.create_index('ix_cascadehistory_pastel_id', 'cascadehistory', ['pastel_id'], unique=False)
    op.create_index('ix_cascadehistory_id', 'cascadehistory', ['id'], unique=False)
    op.create_table('collectionhistory',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('wn_file_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('wn_task_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('task_status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status_messages', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('retry_number', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('pastel_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('collection_task_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['collection_task_id'], ['collection.id'], name='collectionhistory_collection_task_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='collectionhistory_pkey')
    )
    op.create_index('ix_collectionhistory_wn_task_id', 'collectionhistory', ['wn_task_id'], unique=False)
    op.create_index('ix_collectionhistory_wn_file_id', 'collectionhistory', ['wn_file_id'], unique=False)
    op.create_index('ix_collectionhistory_pastel_id', 'collectionhistory', ['pastel_id'], unique=False)
    op.create_index('ix_collectionhistory_id', 'collectionhistory', ['id'], unique=False)
    op.create_table('nfthistory',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('wn_file_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('wn_task_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('task_status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status_messages', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('retry_number', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('pastel_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('nft_task_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['nft_task_id'], ['nft.id'], name='nfthistory_nft_task_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='nfthistory_pkey')
    )
    op.create_index('ix_nfthistory_wn_task_id', 'nfthistory', ['wn_task_id'], unique=False)
    op.create_index('ix_nfthistory_wn_file_id', 'nfthistory', ['wn_file_id'], unique=False)
    op.create_index('ix_nfthistory_pastel_id', 'nfthistory', ['pastel_id'], unique=False)
    op.create_index('ix_nfthistory_id', 'nfthistory', ['id'], unique=False)
    op.drop_index(op.f('ix_sensehistorylog_wn_task_id'), table_name='sensehistorylog')
    op.drop_index(op.f('ix_sensehistorylog_wn_file_id'), table_name='sensehistorylog')
    op.drop_index(op.f('ix_sensehistorylog_task_id'), table_name='sensehistorylog')
    op.drop_index(op.f('ix_sensehistorylog_pastel_id'), table_name='sensehistorylog')
    op.drop_index(op.f('ix_sensehistorylog_id'), table_name='sensehistorylog')
    op.drop_table('sensehistorylog')
    op.drop_index(op.f('ix_nfthistorylog_wn_task_id'), table_name='nfthistorylog')
    op.drop_index(op.f('ix_nfthistorylog_wn_file_id'), table_name='nfthistorylog')
    op.drop_index(op.f('ix_nfthistorylog_task_id'), table_name='nfthistorylog')
    op.drop_index(op.f('ix_nfthistorylog_pastel_id'), table_name='nfthistorylog')
    op.drop_index(op.f('ix_nfthistorylog_id'), table_name='nfthistorylog')
    op.drop_table('nfthistorylog')
    op.drop_index(op.f('ix_collectionhistorylog_wn_task_id'), table_name='collectionhistorylog')
    op.drop_index(op.f('ix_collectionhistorylog_wn_file_id'), table_name='collectionhistorylog')
    op.drop_index(op.f('ix_collectionhistorylog_task_id'), table_name='collectionhistorylog')
    op.drop_index(op.f('ix_collectionhistorylog_pastel_id'), table_name='collectionhistorylog')
    op.drop_index(op.f('ix_collectionhistorylog_id'), table_name='collectionhistorylog')
    op.drop_table('collectionhistorylog')
    op.drop_index(op.f('ix_cascadehistorylog_wn_task_id'), table_name='cascadehistorylog')
    op.drop_index(op.f('ix_cascadehistorylog_wn_file_id'), table_name='cascadehistorylog')
    op.drop_index(op.f('ix_cascadehistorylog_task_id'), table_name='cascadehistorylog')
    op.drop_index(op.f('ix_cascadehistorylog_pastel_id'), table_name='cascadehistorylog')
    op.drop_index(op.f('ix_cascadehistorylog_id'), table_name='cascadehistorylog')
    op.drop_table('cascadehistorylog')
    # ### end Alembic commands ###
