"""cascade tasks db updated

Revision ID: b0e6bfee6eef
Revises: e63284ba92dc
Create Date: 2022-10-25 15:00:28.853079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0e6bfee6eef'
down_revision = 'e63284ba92dc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
