"""cascade tasks db updated

Revision ID: b2f7cb07d3fc
Revises: 828c83605fb0
Create Date: 2022-11-01 17:43:29.759830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2f7cb07d3fc'
down_revision = '828c83605fb0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
