"""Updated table for NFT - nft_dd_file_ipfs_link

Revision ID: bb047a5187a3
Revises: b8a7547c15f1
Create Date: 2023-06-01 20:56:00.889737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb047a5187a3'
down_revision = 'b8a7547c15f1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nft', sa.Column('nft_dd_file_ipfs_link', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nft', 'nft_dd_file_ipfs_link')
    # ### end Alembic commands ###
