"""Added wallet ai=uth related fields

Revision ID: d5bebf95cc98
Revises: 83ae5272ec84
Create Date: 2024-04-23 19:46:01.911138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5bebf95cc98'
down_revision = '83ae5272ec84'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('wallet_id', sa.String(), nullable=True))
    op.add_column('user', sa.Column('wallet_key', sa.String(), nullable=True))
    op.add_column('user', sa.Column('key_salt', sa.String(), nullable=True))
    op.add_column('user', sa.Column('wallet_key_index', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_user_wallet_id'), 'user', ['wallet_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_wallet_id'), table_name='user')
    op.drop_column('user', 'wallet_key_index')
    op.drop_column('user', 'key_salt')
    op.drop_column('user', 'wallet_key')
    op.drop_column('user', 'wallet_id')
    # ### end Alembic commands ###
