"""renamed columns with links to stored files; added column with the ipfs link to original file

Revision ID: e36d7436f379
Revises: 96bfb91e2587
Create Date: 2023-03-29 12:00:32.406103

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e36d7436f379'
down_revision = '96bfb91e2587'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cascade', sa.Column('original_file_ipfs_link', sa.String(), nullable=True))
    op.add_column('cascade', sa.Column('stored_file_ipfs_link', sa.String(), nullable=True))
    op.add_column('cascade', sa.Column('stored_file_aws_link', sa.String(), nullable=True))
    op.add_column('cascade', sa.Column('stored_file_other_links', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('cascade', 'other_links')
    op.drop_column('cascade', 'ipfs_link')
    op.drop_column('cascade', 'aws_link')
    op.add_column('sense', sa.Column('original_file_ipfs_link', sa.String(), nullable=True))
    op.add_column('sense', sa.Column('stored_file_ipfs_link', sa.String(), nullable=True))
    op.add_column('sense', sa.Column('stored_file_aws_link', sa.String(), nullable=True))
    op.add_column('sense', sa.Column('stored_file_other_links', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('sense', 'other_links')
    op.drop_column('sense', 'ipfs_link')
    op.drop_column('sense', 'aws_link')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sense', sa.Column('aws_link', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('sense', sa.Column('ipfs_link', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('sense', sa.Column('other_links', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('sense', 'stored_file_other_links')
    op.drop_column('sense', 'stored_file_aws_link')
    op.drop_column('sense', 'stored_file_ipfs_link')
    op.drop_column('sense', 'original_file_ipfs_link')
    op.add_column('cascade', sa.Column('aws_link', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('cascade', sa.Column('ipfs_link', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('cascade', sa.Column('other_links', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('cascade', 'stored_file_other_links')
    op.drop_column('cascade', 'stored_file_aws_link')
    op.drop_column('cascade', 'stored_file_ipfs_link')
    op.drop_column('cascade', 'original_file_ipfs_link')
    # ### end Alembic commands ###
