"""cascade tasks db updated

Revision ID: e63284ba92dc
Revises: 7611a2bdf505
Create Date: 2022-10-25 14:51:37.599288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e63284ba92dc'
down_revision = '7611a2bdf505'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cascade', sa.Column('wn_file_id', sa.String(), nullable=True))
    op.add_column('cascade', sa.Column('wn_fee', sa.Integer(), nullable=True))
    op.add_column('cascade', sa.Column('burn_txid', sa.String(), nullable=True))
    op.create_index(op.f('ix_cascade_burn_txid'), 'cascade', ['burn_txid'], unique=False)
    op.create_index(op.f('ix_cascade_wn_file_id'), 'cascade', ['wn_file_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cascade_wn_file_id'), table_name='cascade')
    op.drop_index(op.f('ix_cascade_burn_txid'), table_name='cascade')
    op.drop_column('cascade', 'burn_txid')
    op.drop_column('cascade', 'wn_fee')
    op.drop_column('cascade', 'wn_file_id')
    # ### end Alembic commands ###
