"""cascade tasks db updated

Revision ID: e661b0515902
Revises: ff384d2a6f65
Create Date: 2023-01-31 18:06:30.405243

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e661b0515902'
down_revision = 'ff384d2a6f65'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cascade', sa.Column('offer_ticket_txid', sa.String(), nullable=True))
    op.add_column('cascade', sa.Column('offer_ticket_intended_rcpt_pastel_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_cascade_offer_ticket_intended_rcpt_pastel_id'), 'cascade', ['offer_ticket_intended_rcpt_pastel_id'], unique=False)
    op.create_index(op.f('ix_cascade_offer_ticket_txid'), 'cascade', ['offer_ticket_txid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cascade_offer_ticket_txid'), table_name='cascade')
    op.drop_index(op.f('ix_cascade_offer_ticket_intended_rcpt_pastel_id'), table_name='cascade')
    op.drop_column('cascade', 'offer_ticket_intended_rcpt_pastel_id')
    op.drop_column('cascade', 'offer_ticket_txid')
    # ### end Alembic commands ###
