"""Added offer/trasnfer ticket to sense

Revision ID: eafeaaa2b132
Revises: 04c5c21fa78a
Create Date: 2023-06-23 23:50:34.452906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eafeaaa2b132'
down_revision = '04c5c21fa78a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sense', sa.Column('offer_ticket_txid', sa.String(), nullable=True))
    op.add_column('sense', sa.Column('offer_ticket_intended_rcpt_pastel_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_sense_offer_ticket_intended_rcpt_pastel_id'), 'sense', ['offer_ticket_intended_rcpt_pastel_id'], unique=False)
    op.create_index(op.f('ix_sense_offer_ticket_txid'), 'sense', ['offer_ticket_txid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sense_offer_ticket_txid'), table_name='sense')
    op.drop_index(op.f('ix_sense_offer_ticket_intended_rcpt_pastel_id'), table_name='sense')
    op.drop_column('sense', 'offer_ticket_intended_rcpt_pastel_id')
    op.drop_column('sense', 'offer_ticket_txid')
    # ### end Alembic commands ###
