"""preburn tx database

Revision ID: eb0979214a76
Revises: c65b3032ed2e
Create Date: 2022-10-24 16:24:37.276117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb0979214a76'
down_revision = 'c65b3032ed2e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('preburntx',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fee', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('txid', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('NEW', 'PENDING', 'USED', 'BAD', name='pbtxstatus'), nullable=True),
    sa.Column('task_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_preburntx_fee'), 'preburntx', ['fee'], unique=False)
    op.create_index(op.f('ix_preburntx_height'), 'preburntx', ['height'], unique=False)
    op.create_index(op.f('ix_preburntx_id'), 'preburntx', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_preburntx_id'), table_name='preburntx')
    op.drop_index(op.f('ix_preburntx_height'), table_name='preburntx')
    op.drop_index(op.f('ix_preburntx_fee'), table_name='preburntx')
    op.drop_table('preburntx')
    # ### end Alembic commands ###
