"""cascade tasks db updated

Revision ID: ff384d2a6f65
Revises: 7c043c1767f6
Create Date: 2022-12-13 21:42:54.670481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff384d2a6f65'
down_revision = '7c043c1767f6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
