services:
  app:
    image: pastel_data_node:initialized
    container_name: pastel_data_node
    volumes:
      - ../app:/app
      - pastel_data:/root/.pastel
      - ./env:/app/.env
      - ${FILE_STORAGE}:/app/file_storage
    env_file:
      - env
    environment:
      - C_FORCE_ROOT=true # for celery to run as root
    ports:
      - "8090:8090" # FastAPI
      - "4001:4001" # IPFS
      - "5001:5001" # IPFS
      - "9933:9933" # Pastel Network - Mainnet
    depends_on:
      - db
      - redis
#    command: bash -c "while true; do echo 'Container is running'; sleep 60; done"
    command: /scripts/run_app.sh

  db:
    image: postgres:13
    container_name: db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - env
    ports:
      - "5432:5432"

  redis:
    image: redis:6
    container_name: redis
    ports:
      - "6379:6379"

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    env_file:
      - env
    ports:
      - "80:80"
    depends_on:
      - app

volumes:
  postgres_data:
  pastel_data:
    external: true
