version: "3.3"
services:
  
  queue:
    image: redis:alpine
    ports:
      - "6379:6379"

  ipfs:
    image: ipfs.07:latest
    ports:
      - "4001:4001"
      - "4001:4001/udp"
      - "127.0.0.1:5001:5001"
      - "127.0.0.1:8082:8080"
    volumes:
      - /tmp/ipfs-data:/data/ipfs
    build:
      context: ../backend
      dockerfile: ipfs.07.dockerfile
      args:
        INSTALL_DEV: ${INSTALL_DEV-false}

  wn1:
    image: wn-testnet:test
    ports:
      - "8181:8080"
      - "19932:19932"
    env_file:
      - .env
    build:
      context: ../backend
      dockerfile: wn-testnet.dockerfile
      args:
        INSTALL_DEV: ${INSTALL_DEV-false}


  test:
    image: nginx
    ports:
        - 7777:80
    volumes:
        - ./:/usr/share/nginx/html
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
          HOST_IP: ${DOCKER_GATEWAY_HOST:-host.docker.internal}
